//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDictionaryCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataDictionaryCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished setting key descriptions.
        /// </summary>
        internal static string AdvancedSettingsKeyDescriptonsEndAction {
            get {
                return ResourceManager.GetString("AdvancedSettingsKeyDescriptonsEndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting descriptions.
        /// </summary>
        internal static string AdvanceSettingsKeyDescriptionsBeginAction {
            get {
                return ResourceManager.GetString("AdvanceSettingsKeyDescriptionsBeginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Dictionary Creator {0}.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been updated and will now restart..
        /// </summary>
        internal static string ApplicationUpdated {
            get {
                return ResourceManager.GetString("ApplicationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A login with DBO permission is required..
        /// </summary>
        internal static string ConnectionErrorDBORequired {
            get {
                return ResourceManager.GetString("ConnectionErrorDBORequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection failed. See Connect To Database tab for details..
        /// </summary>
        internal static string ConnectionErrorGeneric {
            get {
                return ResourceManager.GetString("ConnectionErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your database connection failed. Please try again. You may use the connection string builder by clicking the ellipse to the right..
        /// </summary>
        internal static string ConnectionErrorGenericDetailed {
            get {
                return ResourceManager.GetString("ConnectionErrorGenericDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for table descriptions and additional properties using the grid and tools below..
        /// </summary>
        internal static string ConnectionInstructionsConnected {
            get {
                return ResourceManager.GetString("ConnectionInstructionsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid database connection has been established.  Visit the Connect to Database tab to continue..
        /// </summary>
        internal static string ConnectionInstructionsNotConnected {
            get {
                return ResourceManager.GetString("ConnectionInstructionsNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not currently connected. Please specify a database to document..
        /// </summary>
        internal static string ConnectionNotConnected {
            get {
                return ResourceManager.GetString("ConnectionNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently connected to {0}/{1}. You may immediately begin documenting the database, but advanced settings may faciliate the process.  We suggest you visit this tab first..
        /// </summary>
        internal static string ConnectionSuccessGeneric {
            get {
                return ResourceManager.GetString("ConnectionSuccessGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot install the latest version of the application. \r\nPlease check your network connection, or try again later. Error: {0}.
        /// </summary>
        internal static string DeploymentDownloadExceptionMessage {
            get {
                return ResourceManager.GetString("DeploymentDownloadExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up for documentation..
        /// </summary>
        internal static string DocumentationSetupBeginAction {
            get {
                return ResourceManager.GetString("DocumentationSetupBeginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading table..
        /// </summary>
        internal static string DocumentLoadTableBeginAction {
            get {
                return ResourceManager.GetString("DocumentLoadTableBeginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table load completed..
        /// </summary>
        internal static string DocumentLoadTableEndAction {
            get {
                return ResourceManager.GetString("DocumentLoadTableEndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 276.
        /// </summary>
        internal static string DocumentMaxGridHeight {
            get {
                return ResourceManager.GetString("DocumentMaxGridHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document setup complete..
        /// </summary>
        internal static string DocumentSetupEndAction {
            get {
                return ResourceManager.GetString("DocumentSetupEndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed export.
        /// </summary>
        internal static string ExportEndAction {
            get {
                return ResourceManager.GetString("ExportEndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got an error starting the program.  There might be no system default for this file type..
        /// </summary>
        internal static string ExportErrorGeneric {
            get {
                return ResourceManager.GetString("ExportErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed import..
        /// </summary>
        internal static string ImportEndAction {
            get {
                return ResourceManager.GetString("ImportEndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to validate script as a valid export script..
        /// </summary>
        internal static string ImportErrorCanNotValidateScript {
            get {
                return ResourceManager.GetString("ImportErrorCanNotValidateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import file was not exported by a current version of this program..
        /// </summary>
        internal static string ImportErrorUnsupportedVersion {
            get {
                return ResourceManager.GetString("ImportErrorUnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0}.[{1}] does not exist..
        /// </summary>
        internal static string MissingColumnException {
            get {
                return ResourceManager.GetString("MissingColumnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table {0} does not exist..
        /// </summary>
        internal static string MissingTableException {
            get {
                return ResourceManager.GetString("MissingTableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required update is available, which will be installed now..
        /// </summary>
        internal static string RequiredUpdateAvailable {
            get {
                return ResourceManager.GetString("RequiredUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting table description..
        /// </summary>
        internal static string TableDescriptionBeginAction {
            get {
                return ResourceManager.GetString("TableDescriptionBeginAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table description set..
        /// </summary>
        internal static string TableDescriptionEndAction {
            get {
                return ResourceManager.GetString("TableDescriptionEndAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to update the application now?.
        /// </summary>
        internal static string UpdateApplicationNow {
            get {
                return ResourceManager.GetString("UpdateApplicationNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
    }
}
